apiVersion: v1
kind: Service
metadata:
  name: books-db
  labels:
    env: dev
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    env: dev
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: books-db
  labels:
    env: dev
spec:
  minReadySeconds: 4
  replicas: 2
  selector:
    matchLabels:
      env: dev
  serviename: books-db # this should be service name  
  template:
    metadata:
      name: book-pos
      labels:
        env: dev
    spec:
      containers:
        - name: booksdb
          image: postgres:15-alpine
          resources:
            requests:
              memory: "24Mi" 
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "50
          envFrom:
            - configMapRef:
                name: config-db1
          volumeMounts:
            - name: books-vol
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432     
  volumeClaimTemplates:
    - metadata:
        name: books-vol
        labels:
          env: dev
      spec:
        accessModes:
          - ReadWriteOnce
        selector:
          env: dev
        storageClassName: managed
        resources:
          requests:
            storage: 1Gi
        
