---
apiVersion: v1
kind: Service
metadata:
  name: book-sv-db
  labels:
    env: dev
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    env: dev
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: book-sv-db
  labels:
    env: dev
spec:
  minReadySeconds: 4
  replicas: 2
  selector:
    matchLabels:
      env: dev
  serviceName: book-sv-db # this should be service name  
  template:
    metadata:
      name: book-sv-pos
      labels:
        env: dev
    spec:
      containers:
        - name: book-svdb
          image: shaikkhajaibrahim/libbookssvc:1.0
          resources:
            requests:
              memory: "24Mi" 
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "300m"
          envFrom:
            - configMapRef:
                name: config-db2
          volumeMounts:
            - name: book-sv-vol
              mountPath: /var/lib/postgresql/data
              subPath: data
          ports:
            - containerPort: 5432     
  volumeClaimTemplates:
    - metadata:
        name: book-sv-vol
        labels:
          env: dev
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: managed
        resources:
          requests:
            storage: 1Gi
        
