apiVersion: v1
kind: Pod
metadata:
  name: web-one
  labels:
    env: dev
  namespace: first-sample   
spec:
  containers:
    - name: sam
      image: nginx
      ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata: 
  name: ser-1
  labels:
    env: dev
  namespace: first-sample
spec:
  type: ClusterIP
  selector:
    name: web-one
  ports:
    - port: 8080              
