apiVersion: v1
kind: Pod
metadata:
  name: web-one
  labels:
    env: dev
  namespace: first-sample   
spec:
  containers:
    - name: sam
      image: nginx
      ports:
        - containerPort: 80  