---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: source
  labels:
    app: frontend
    env: production
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      env: production
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: source
      labels:
        app: frontend
        env: production
      annotations:
    spec:
      containers:
      - name: web
        image: shaikkhajaibrahim/dmtest:2.0
        resources:
          requests:
            memory: 24Mi
            cpu: 50m
          limits:
            memory: 24Mi
            cpu: 50m
        ports:
          - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: web-sv
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
                       

