---
apiVersion: v1
kind: Service
metadata:
  name: ser-first
  labels: 
    env: dev
spec:
  type: ClusterIP
  selector:
    db: books
  ports:
    - port: 5432      
      targetPort: 5432  
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: firstsimple
  labels:
    env: dev
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchLabels:
      env: dev
  serviceName: booksdb-svc
  template:
    metadata:
      name: go-first
      labels:
        env: dev    
    spec:
      containers:
        - name: bools-db
          image: postgres:15-alpine
          resources:
            requests:
              memory: 24M
              cpu: 100m
            limits:
              memory: 128M
              cpu: 500m  
          envFrom:
            - configMapRef:
                name: config-db 
          ports:
            - containerPort: 5432 
          volumeMounts:
            - name: books-db
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: books-db
        labels:
          env: dev 
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: master
        selector:
          matchLabels:
            env: dev
        resources:
          requests:
            storage: 1Gi     