---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-db
  labels:
    env: dev 
data:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: usersdb  


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-db2
  labels:
    env: dev 
data:
   SECRET_KEY: 'YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k'
   DATABASE_URL: postgresql://user:password@book-db:5432/booksdb
