apiVersion: v1
kind: Service
metadata:
  name: samplefirst
  labels:
    env: de
    qt: pt
spec:
  type: NodePort
  selector:
    env: dev
    qt: env
  ports:
   - port: 8080
     targetPort: 8080  
