apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-sv
  labels:
    env: back
  annotations:
    first: book-sv
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      env: back  # Ensure this matches the labels in the pod template
  template:
    metadata:
      labels:
        env: back
      annotations:
        first: book-sv        
    spec:
      containers:
        - name: book-sv
          image: shaikkhajaibrahim/libbookssvc:1.0
          resources:
            requests:
              memory: "24Mi"  # Use "Mi" for mebibytes
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"  
          env:
            - configMapRef:
              name: config-db2                     
          ports:
            - containerPort: 8000  # Correctly formatted as a list item

---
apiVersion: v1
kind: Service
metadata:
  name: book-sv
  labels:
    env: back  # Updated label to match the Deployment's environment label
spec:
  type: ClusterIP
  selector:
    env: back  # Ensure this matches the labels in the Deployment template
  ports:
    - port: 8000       # The port exposed by the service
      targetPort: 8000 # The port on the container to forward traffic to 