apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-db
  labels:
    env: db
  annotations:
    first: db-book
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      env: db  # Ensure this matches the labels in the pod template
  template:
    metadata:
      labels:
        env: db
      annotations:
        first: db-book        
    spec:
      containers:
        - name: bookdb
          image: postgres:15-alpine
          envFrom:
            - configMapRef:
               name: config-db                                   
          resources:
            requests:
              memory: "24Mi"  # Use "Mi" for mebibytes
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"  
          ports:
            - containerPort: 5432  # Ensure correct formatting here

---
apiVersion: v1
kind: Service
metadata:
  name: book-db
  labels:
    env: db
spec:
  type: ClusterIP
  selector:
    env: db  # Ensure this matches the labels in the Deployment template
  ports:
    - port: 5432       # The port exposed by the service
      targetPort: 5432 # The port on the container to forward traffic to  
