---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-sv
  labels:
    env: back
  annotations:
    first: users-sv
spec:
  minReadySeconds: 5
  replicas: 1
  template:
    metadata:
      name: users-sv
      labels:
        env: back
      annotations:
        first: users-sv        
    spec:
      containers:
        - name: users-sv
          image: postgres:15-alpine
          env:
            - name: SECRET_KEY
              value: 'YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k'
            - name: DATABASE_URL
              value: "postgresql://user:password@users-db:5432/usersdb
          resources:
            requests:
              memory: 24M
              cpu: 100m
            limits:
              memory: 128M
              cpu: 500m  
          ports:
            containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: user-sv
  labels:
    env: db
spec:
  type: ClusterIP
  selector:
    env: back
  ports:
    - port: 5432
      targetPort: 5432  
