apiVersion: v1
kind: ConfigMap
metadata:
  name: config-db
  labels:
    env: dev
  namespace: first-sample
  annotations: 
    name: first
data:
  POSTGRES_DB: mydatabase
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: password 
