apiVersion: v1
kind: Pod
metadata:
  name: web-sec
  labels:
    env: dev
  namespace: first-sample
  annotations:
    first: dev
spec:
  containers:
    - name: web
      image: postgres:17
      resources:
        requests:
          cpu: "250m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "512Mi"
      envFrom:
        - configMapRef:
          name: config-db
          ports:
            - containerPort: 80
      volumeMounts:
        - name: m-db1
          mountPath: var/lib/postgresql/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc
  labels:
    env: dev
  namespace: first-sample
spec:
                      



