
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pre-skate
  labels: 
    env: dev
  namespace: first-sample
  annotations:
    name: chandu
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: pre-skate
      labels:
        env: dev
      namespace: first-sample
      annotations:
        name: chandu
    spec:
      containers:
        - name: skate
          image: shaikkhajaibrahim/skateboard:1.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pre-skate
  labels:
    env: dev
  namespace: first-sample
  annotations:
    name: chandu
spec:
  selector:
    env: dev
  ports:
  - port: 80
    targetPort: 80
